# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

BSbasis <- function(t, d0) {
    .Call(`_csNet_BSbasis`, t, d0)
}

checkDAG <- function(G) {
    .Call(`_csNet_checkDAG`, G)
}

updates <- function(B, X, T, t, a, a0 = 0.1, b0 = 0.1) {
    .Call(`_csNet_updates`, B, X, T, t, a, a0, b0)
}

updateG <- function(X, T, G, s, t, r, z, v) {
    .Call(`_csNet_updateG`, X, T, G, s, t, r, z, v)
}

updater <- function(G, a0 = 1, b0 = 1) {
    .Call(`_csNet_updater`, G, a0, b0)
}

updatet <- function(B, X, T, s, t, a, s0 = 0.1) {
    .Call(`_csNet_updatet`, B, X, T, s, t, a, s0)
}

updatev <- function(B, v, a0 = 1, b0 = 1e-1) {
    .Call(`_csNet_updatev`, B, v, a0, b0)
}

updatez <- function(a, z, a0 = 1, b0 = 0.1) {
    .Call(`_csNet_updatez`, a, z, a0, b0)
}

updatea <- function(B, X, T, s, t, z) {
    .Call(`_csNet_updatea`, B, X, T, s, t, z)
}

updateB <- function(B, X, T, G, s, t, a, v) {
    .Call(`_csNet_updateB`, B, X, T, G, s, t, a, v)
}

